### PR TITLE
Only add I/O Parameters panel if there are any source or target product.

### PR DESCRIPTION
**Pull request by obarrilero**

### CODE REVIEW

**Comment by marpet** [comment]
What is the good for? What shall be processed if there is no I/O?

**Comment by obarrilero** [comment]
It is made for the StoredGraphOp. In this operator, the only processing parameter is the xml file, and there are no input or output products directly selected by the user (they are defined in the xml file).

**Comment by marpet** [comment]
Is this needed as a separate operator? The Batch Processing can do it already and the sources can be exchanged.

**Comment by obarrilero** [comment]
It is for being able to run the graphs from the benchmark (we created an internal operator). This operator is already released and this modification is only to fix one of the issues from MF. Perhaps in the future we could investigate if it is possible to use the Batch Processing from the Benchmark

**Comment by marpet** [comment]
Ah, I see. OK.

**Comment by obarrilero** [comment]
Thank you!

**Pull request merged**
