### PR TITLE
Service loading should be done in background task

### PR DESCRIPTION
**Pull request by Florian1209**
move initializing task to onShowing function
- initImageIO
- third party libs by Cl
- initGPF

### CODE REVIEW

**Comment by lveci** [comment]
I don't think these affect the start up time that much. If the product library tab was previously available on the right hand side toolbar, next time you start SNAP it will take > 20secs after desktop has come up before you can do anything.

**Comment by Florian1209** [comment]
@lveci I can't reproduce the issue described. 
I have downloaded from product library an S1 product, stop SNAP and restart. The starting is not slow down.
Do you use a specific repository?

**Comment by lveci** [comment]
In the profiler it shows most of the time spent on getConnection 6 times. I assume this is for the 6 default repositories.

image

Maybe the connection to a repository should only be needed when that repo is used by the user?

**Comment by Florian1209** [comment]
The delay >20 sec is not visible here. Why this connection could take more than 2 seconds?
@a-draghici Maybe you have a idea about this issue?

**Comment by a-draghici** [comment]
Hi @Florian1209 ,
This connection could take more than 2 seconds because it opens an H2 database file used by Product Library to store information about downloaded products from remote repositories.
The slow down happens when the connection with H2 database is established for first time after opening SNAP.

**Comment by marpet** [comment]
I had a quick look at the code. The class DataAccess has only static methods. for every method call a new connection need to be created to the DB. The connection could be established once in the initialize method and then reused in the other methods. Could this help?

**Pull request closed without merging**
