### PR TITLE
Graph builder : manage tiepoint grid source input parameter

### PR DESCRIPTION
**Pull request by Florian1209**
add ui to select tiepoint grid source in subset and read operator (advanced option).

### CODE REVIEW

**Comment by oanahogoiu** [comment]
Florian, which was the specific request for this? (is there a JIRA?) 
The tiepoint grid should be also available from GPT?

**Comment by Florian1209** [comment]
No I don't have a specific task on JIRA. I will created on for it.
I do this firstly for gpt to fix the gpt test using sentinel product (there were shifting of band/tiepointgrids index in expected value). There is an other PR for snap-engine.

**Comment by marpet** [comment]
The fix should not be to exclude the tie-point grids from the tests?
Also I don't like to have things duplicated. In the ReadOp and in the SubsetOp.

**Comment by Florian1209** [comment]
@marco Yes, in the sentinel2 reader gpt test I add tie point grid selection with 3 ECWMF tie point grid (I have a gpt test commit on my local for it). For other test that it don't use tiepoint grid I think it's more lighter to exclude this data with subset.
For readerOp, I see it's used in gpt tests instead of subset and I thought there was a reason to it (maybe it 's more lighter than subset op).

**Comment by Florian1209** [comment]
@marpet 
Further, the additionnal tie point grid are not resized during the subset gpt test.
during the Subset_S2_B1B2_Ref 
-> errorINFO: org.esa.snap.core.datamodel.Product: raster width 1196 not equal to 10980
Should the spatial subset be updated for the tiepoint grid?

**Comment by Florian1209** [comment]
I have a fix for tiepoint grid in sentinel2 reader.
I close this PR.

**Pull request closed without merging**
