### PR TITLE
move credentials to snap-engine

### PR DESCRIPTION
**Pull request by lveci**

### CODE REVIEW

**Review by a-draghici — CHANGES_REQUESTED** [review]
There are some compilation errors.
Please check your changes. I think you forget to commit all modifed files.
Thank you in advance.

**Comment by lveci** [comment]
What's missing? I don't have any compile error. The travis errors above are because it needs the changes from snap-engine first.

**Comment by a-draghici** [comment]
The compilation errors are fixed.
Now, when SNAP starts the error occurs:
image
Do you reproduce this issue?
Thank you in advance.

**Review by a-draghici — APPROVED** [review]

**Comment by a-draghici** [comment]
Thank you for the solution.
Now all is ok and I'll approve the pull requests.
Best regards.

**Pull request merged**
