### PR TITLE
Snap 970

### PR DESCRIPTION
**Pull request by Florian1209**

### CODE REVIEW

**Comment by marpet** [comment]
@lveci Luis, can you check the changes in CreateLandMaskOpUI?

I would say the op should be changed too. I don't see the necessary changes yet. 
The help pages for the operator needs to be updated too. It is not in sync with the operator anymore. Images need to be updated.

@Florian1209 Would if thihs PR would have been split into two. Because the binning and the landmaskOp are affected. It is easier to discuss when this is seperated.

**Review by marpet — CHANGES_REQUESTED** [review]
The help pages for the Binning must be updated accordingly.
And see the general comment, too.

**Comment by Florian1209** [comment]
How can I configure SNAP ui options (Linux) to create screen shot as in the actual documentation ?
Should I switch on windows ? 
Thanks

**Review by lveci — APPROVED** [review]
without the landmaskUI changes it looks ok

**Comment by marpet** [comment]
Use the Linux GUI. The screen shots in the help are already a mixture of several operating systems and versions.
Just ensure that, within the help of one module the screenshots are consistent.

**Review by Florian1209 — COMMENTED** [review]
Changes done

**Pull request closed without merging**
