### PR TITLE
SNAP-3517_snap-product-library-ui-v2

### PR DESCRIPTION
**Pull request by a-draghici**
Fix for [SNAP-3517](https://senbox.atlassian.net/browse/SNAP-3517).

[SNAP-3517]: https://senbox.atlassian.net/browse/SNAP-3517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by marpet** [comment]
I'm not sure if replacing all is necessary. I just want to ensure that no wrong times are displayed to the user.

**Comment by a-draghici** [comment]
> I'm not sure if replacing all is necessary. I just want to ensure that no wrong times are displayed to the user.

I understand. I'll check it.

**Comment by a-draghici** [comment]
> > I'm not sure if replacing all is necessary. I just want to ensure that no wrong times are displayed to the user.
> 
> I understand. I'll check it.

I'll checked with an S2 product from Scientific Data Hub by matching the acquisition date displayed on UI (on search results and from All local Folders) and the acquisition date from the product name, it matches.

**Comment by marpet** [comment]
Then it might be okay.

**Review by marpet — APPROVED** [review]

**Review by dianaharosa — APPROVED** [review]

**Pull request merged**
