### PR TITLE
SNAP-1579_green_man_and_plugin_category

### PR DESCRIPTION
**Pull request by blucian**
Fixed the incorrect association with plugin category 
Updated plugin category icons

### CODE REVIEW

**Comment by TomBlock** [comment]
Are these icons open-source, royalty free and without other legal issues?

**Comment by marpet** [comment]
It would also be good to align the naming of the files with already existing Icons. CamelCase, no underline, not prefixed with icon.

**Comment by blucian** [comment]
THe icons are form here: http://www.small-icons.com/packs/16x16-free-application-icons.htm

The licence is Creative Commons Attribution-Share Alike 3.0 License.

**Comment by marpet** [comment]
Okay, Thanks. In this case can you please add an entry to the two files THIRDPARTY_LICENSES.txt. One is in snap-engine and the other in snap-desktop/snap-rcp

**Review by kraftek — APPROVED** [review]

**Comment by kraftek** [comment]
Don't forget to add an entry to the two files THIRDPARTY_LICENSES.txt

**Pull request merged**
