### PR TITLE
SNAP-1057 add resampling operation parameters in case of multi-size products

### PR DESCRIPTION
**Pull request by Florian1209**
The source product is resampled with a reference band size. This operation occur before to apply the land mask operator .
The reference band will be selected by user.
The interpolation stay simple with nearest model.

### CODE REVIEW

**Review by lveci — COMMENTED** [review]
Is this really the best solution for multi-sized bands?
Should every operator need to have a reference band parameter to resample?
Or is it a simpler component design to require a resampling operation before it?

**Comment by Florian1209** [comment]
Indeed, it's a simpler component design.
Maybe the operator would remain unchanged.
I would implement a kind of graph builder to chain the resampling operator and the  land mask.
Is there a similar example of processor chain in SNAP?
Maybe you have an other idea or an other solution?

**Comment by lveci** [comment]
For multi-size bands in SAR, it generally requires more than just a resample. For bust data it has to be deburst and subswath merged then all the bands become the same size and a user can apply an operator like land mask as usual.

**Comment by marpet** [comment]
I was already sceptical for the PR https://github.com/senbox-org/snap-desktop/pull/126
Extending every operator with a resampling functionality does actually not follow the idea of GPF.
Also, using a reference band as parameter might not be enough. Users might want to resample to a different resolution. Also, how the data is up and down sampled must be parameterised. Otherwise, a user gets unwanted results.
I think it is better to keep things separate. A default graph file could be added to the graph builder which is doing this.

**Comment by Florian1209** [comment]
@marpet
It 's meaning the user have to use graph builder UI to execute the land mask or the binning operator in case of multi-size product.
Or is there a way to use a custom interface (current operator ui + complete resampling operator ui) and the graph builder engine?

**Comment by Florian1209** [comment]
The user could be redirected to the graph builder editor with a default graph (read > resampling> current operator needs resampling) loaded with the current source product? The redirection should be triggered by the  uncompatibility multi-size source product exception of current operator(after confirmation dialog).

**Comment by marpet** [comment]
The operators can be used one after the other. In SNAP Desktop chose first from the menu `Raster / Geometric / Resampling` or `Optical / Geometric / S2 Resampling Processor` and afterwards the result can be used in the land mask operator.

**Comment by Florian1209** [comment]
@marpet yes of course.
Moreover, if the user apply the land mask operator in graph builder editor without the resampling proc, he could be encountered the same issue during processing. The same for user snap engine or user command line user.
Is there a solution to join the different use cases without to having user come back?
Or simple add new exception messages at source selection product step could be efficient (+ suggested default graph)?

**Review by lveci — APPROVED** [review]
The check for hasMultiSizeProducts is not UI specific and should be called from initialize() so an error could be thrown when processing with gpt or by using the operator on it's own

**Pull request merged**
